// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newGoadminRoleUser(db *gorm.DB, opts ...gen.DOOption) goadminRoleUser {
	_goadminRoleUser := goadminRoleUser{}

	_goadminRoleUser.goadminRoleUserDo.UseDB(db, opts...)
	_goadminRoleUser.goadminRoleUserDo.UseModel(&model.GoadminRoleUser{})

	tableName := _goadminRoleUser.goadminRoleUserDo.TableName()
	_goadminRoleUser.ALL = field.NewAsterisk(tableName)
	_goadminRoleUser.RoleID = field.NewInt32(tableName, "role_id")
	_goadminRoleUser.UserID = field.NewInt32(tableName, "user_id")
	_goadminRoleUser.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminRoleUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminRoleUser.fillFieldMap()

	return _goadminRoleUser
}

type goadminRoleUser struct {
	goadminRoleUserDo goadminRoleUserDo

	ALL       field.Asterisk
	RoleID    field.Int32
	UserID    field.Int32
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (g goadminRoleUser) Table(newTableName string) *goadminRoleUser {
	g.goadminRoleUserDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goadminRoleUser) As(alias string) *goadminRoleUser {
	g.goadminRoleUserDo.DO = *(g.goadminRoleUserDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goadminRoleUser) updateTableName(table string) *goadminRoleUser {
	g.ALL = field.NewAsterisk(table)
	g.RoleID = field.NewInt32(table, "role_id")
	g.UserID = field.NewInt32(table, "user_id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *goadminRoleUser) WithContext(ctx context.Context) *goadminRoleUserDo {
	return g.goadminRoleUserDo.WithContext(ctx)
}

func (g goadminRoleUser) TableName() string { return g.goadminRoleUserDo.TableName() }

func (g goadminRoleUser) Alias() string { return g.goadminRoleUserDo.Alias() }

func (g goadminRoleUser) Columns(cols ...field.Expr) gen.Columns {
	return g.goadminRoleUserDo.Columns(cols...)
}

func (g *goadminRoleUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goadminRoleUser) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["role_id"] = g.RoleID
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminRoleUser) clone(db *gorm.DB) goadminRoleUser {
	g.goadminRoleUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goadminRoleUser) replaceDB(db *gorm.DB) goadminRoleUser {
	g.goadminRoleUserDo.ReplaceDB(db)
	return g
}

type goadminRoleUserDo struct{ gen.DO }

func (g goadminRoleUserDo) Debug() *goadminRoleUserDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminRoleUserDo) WithContext(ctx context.Context) *goadminRoleUserDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminRoleUserDo) ReadDB() *goadminRoleUserDo {
	return g.Clauses(dbresolver.Read)
}

func (g goadminRoleUserDo) WriteDB() *goadminRoleUserDo {
	return g.Clauses(dbresolver.Write)
}

func (g goadminRoleUserDo) Session(config *gorm.Session) *goadminRoleUserDo {
	return g.withDO(g.DO.Session(config))
}

func (g goadminRoleUserDo) Clauses(conds ...clause.Expression) *goadminRoleUserDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminRoleUserDo) Returning(value interface{}, columns ...string) *goadminRoleUserDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goadminRoleUserDo) Not(conds ...gen.Condition) *goadminRoleUserDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminRoleUserDo) Or(conds ...gen.Condition) *goadminRoleUserDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminRoleUserDo) Select(conds ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminRoleUserDo) Where(conds ...gen.Condition) *goadminRoleUserDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminRoleUserDo) Order(conds ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminRoleUserDo) Distinct(cols ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminRoleUserDo) Omit(cols ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminRoleUserDo) Join(table schema.Tabler, on ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminRoleUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminRoleUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminRoleUserDo) Group(cols ...field.Expr) *goadminRoleUserDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminRoleUserDo) Having(conds ...gen.Condition) *goadminRoleUserDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminRoleUserDo) Limit(limit int) *goadminRoleUserDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminRoleUserDo) Offset(offset int) *goadminRoleUserDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminRoleUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminRoleUserDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminRoleUserDo) Unscoped() *goadminRoleUserDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminRoleUserDo) Create(values ...*model.GoadminRoleUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminRoleUserDo) CreateInBatches(values []*model.GoadminRoleUser, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminRoleUserDo) Save(values ...*model.GoadminRoleUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminRoleUserDo) First() (*model.GoadminRoleUser, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRoleUser), nil
	}
}

func (g goadminRoleUserDo) Take() (*model.GoadminRoleUser, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRoleUser), nil
	}
}

func (g goadminRoleUserDo) Last() (*model.GoadminRoleUser, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRoleUser), nil
	}
}

func (g goadminRoleUserDo) Find() ([]*model.GoadminRoleUser, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoadminRoleUser), err
}

func (g goadminRoleUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoadminRoleUser, err error) {
	buf := make([]*model.GoadminRoleUser, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminRoleUserDo) FindInBatches(result *[]*model.GoadminRoleUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminRoleUserDo) Attrs(attrs ...field.AssignExpr) *goadminRoleUserDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminRoleUserDo) Assign(attrs ...field.AssignExpr) *goadminRoleUserDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminRoleUserDo) Joins(fields ...field.RelationField) *goadminRoleUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goadminRoleUserDo) Preload(fields ...field.RelationField) *goadminRoleUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goadminRoleUserDo) FirstOrInit() (*model.GoadminRoleUser, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRoleUser), nil
	}
}

func (g goadminRoleUserDo) FirstOrCreate() (*model.GoadminRoleUser, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRoleUser), nil
	}
}

func (g goadminRoleUserDo) FindByPage(offset int, limit int) (result []*model.GoadminRoleUser, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goadminRoleUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goadminRoleUserDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goadminRoleUserDo) Delete(models ...*model.GoadminRoleUser) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goadminRoleUserDo) withDO(do gen.Dao) *goadminRoleUserDo {
	g.DO = *do.(*gen.DO)
	return g
}
