// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newGoadminPermission(db *gorm.DB, opts ...gen.DOOption) goadminPermission {
	_goadminPermission := goadminPermission{}

	_goadminPermission.goadminPermissionDo.UseDB(db, opts...)
	_goadminPermission.goadminPermissionDo.UseModel(&model.GoadminPermission{})

	tableName := _goadminPermission.goadminPermissionDo.TableName()
	_goadminPermission.ALL = field.NewAsterisk(tableName)
	_goadminPermission.ID = field.NewInt32(tableName, "id")
	_goadminPermission.Name = field.NewString(tableName, "name")
	_goadminPermission.Slug = field.NewString(tableName, "slug")
	_goadminPermission.HTTPMethod = field.NewString(tableName, "http_method")
	_goadminPermission.HTTPPath = field.NewString(tableName, "http_path")
	_goadminPermission.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminPermission.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminPermission.fillFieldMap()

	return _goadminPermission
}

type goadminPermission struct {
	goadminPermissionDo goadminPermissionDo

	ALL        field.Asterisk
	ID         field.Int32
	Name       field.String
	Slug       field.String
	HTTPMethod field.String
	HTTPPath   field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (g goadminPermission) Table(newTableName string) *goadminPermission {
	g.goadminPermissionDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goadminPermission) As(alias string) *goadminPermission {
	g.goadminPermissionDo.DO = *(g.goadminPermissionDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goadminPermission) updateTableName(table string) *goadminPermission {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.Name = field.NewString(table, "name")
	g.Slug = field.NewString(table, "slug")
	g.HTTPMethod = field.NewString(table, "http_method")
	g.HTTPPath = field.NewString(table, "http_path")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *goadminPermission) WithContext(ctx context.Context) *goadminPermissionDo {
	return g.goadminPermissionDo.WithContext(ctx)
}

func (g goadminPermission) TableName() string { return g.goadminPermissionDo.TableName() }

func (g goadminPermission) Alias() string { return g.goadminPermissionDo.Alias() }

func (g goadminPermission) Columns(cols ...field.Expr) gen.Columns {
	return g.goadminPermissionDo.Columns(cols...)
}

func (g *goadminPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goadminPermission) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 7)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["slug"] = g.Slug
	g.fieldMap["http_method"] = g.HTTPMethod
	g.fieldMap["http_path"] = g.HTTPPath
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminPermission) clone(db *gorm.DB) goadminPermission {
	g.goadminPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goadminPermission) replaceDB(db *gorm.DB) goadminPermission {
	g.goadminPermissionDo.ReplaceDB(db)
	return g
}

type goadminPermissionDo struct{ gen.DO }

func (g goadminPermissionDo) Debug() *goadminPermissionDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminPermissionDo) WithContext(ctx context.Context) *goadminPermissionDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminPermissionDo) ReadDB() *goadminPermissionDo {
	return g.Clauses(dbresolver.Read)
}

func (g goadminPermissionDo) WriteDB() *goadminPermissionDo {
	return g.Clauses(dbresolver.Write)
}

func (g goadminPermissionDo) Session(config *gorm.Session) *goadminPermissionDo {
	return g.withDO(g.DO.Session(config))
}

func (g goadminPermissionDo) Clauses(conds ...clause.Expression) *goadminPermissionDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminPermissionDo) Returning(value interface{}, columns ...string) *goadminPermissionDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goadminPermissionDo) Not(conds ...gen.Condition) *goadminPermissionDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminPermissionDo) Or(conds ...gen.Condition) *goadminPermissionDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminPermissionDo) Select(conds ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminPermissionDo) Where(conds ...gen.Condition) *goadminPermissionDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminPermissionDo) Order(conds ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminPermissionDo) Distinct(cols ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminPermissionDo) Omit(cols ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminPermissionDo) Join(table schema.Tabler, on ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminPermissionDo) Group(cols ...field.Expr) *goadminPermissionDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminPermissionDo) Having(conds ...gen.Condition) *goadminPermissionDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminPermissionDo) Limit(limit int) *goadminPermissionDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminPermissionDo) Offset(offset int) *goadminPermissionDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminPermissionDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminPermissionDo) Unscoped() *goadminPermissionDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminPermissionDo) Create(values ...*model.GoadminPermission) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminPermissionDo) CreateInBatches(values []*model.GoadminPermission, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminPermissionDo) Save(values ...*model.GoadminPermission) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminPermissionDo) First() (*model.GoadminPermission, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminPermission), nil
	}
}

func (g goadminPermissionDo) Take() (*model.GoadminPermission, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminPermission), nil
	}
}

func (g goadminPermissionDo) Last() (*model.GoadminPermission, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminPermission), nil
	}
}

func (g goadminPermissionDo) Find() ([]*model.GoadminPermission, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoadminPermission), err
}

func (g goadminPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoadminPermission, err error) {
	buf := make([]*model.GoadminPermission, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminPermissionDo) FindInBatches(result *[]*model.GoadminPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminPermissionDo) Attrs(attrs ...field.AssignExpr) *goadminPermissionDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminPermissionDo) Assign(attrs ...field.AssignExpr) *goadminPermissionDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminPermissionDo) Joins(fields ...field.RelationField) *goadminPermissionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goadminPermissionDo) Preload(fields ...field.RelationField) *goadminPermissionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goadminPermissionDo) FirstOrInit() (*model.GoadminPermission, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminPermission), nil
	}
}

func (g goadminPermissionDo) FirstOrCreate() (*model.GoadminPermission, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminPermission), nil
	}
}

func (g goadminPermissionDo) FindByPage(offset int, limit int) (result []*model.GoadminPermission, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goadminPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goadminPermissionDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goadminPermissionDo) Delete(models ...*model.GoadminPermission) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goadminPermissionDo) withDO(do gen.Dao) *goadminPermissionDo {
	g.DO = *do.(*gen.DO)
	return g
}
