// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newGoadminUser(db *gorm.DB, opts ...gen.DOOption) goadminUser {
	_goadminUser := goadminUser{}

	_goadminUser.goadminUserDo.UseDB(db, opts...)
	_goadminUser.goadminUserDo.UseModel(&model.GoadminUser{})

	tableName := _goadminUser.goadminUserDo.TableName()
	_goadminUser.ALL = field.NewAsterisk(tableName)
	_goadminUser.ID = field.NewInt32(tableName, "id")
	_goadminUser.Username = field.NewString(tableName, "username")
	_goadminUser.Password = field.NewString(tableName, "password")
	_goadminUser.Name = field.NewString(tableName, "name")
	_goadminUser.Avatar = field.NewString(tableName, "avatar")
	_goadminUser.RememberToken = field.NewString(tableName, "remember_token")
	_goadminUser.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminUser.fillFieldMap()

	return _goadminUser
}

type goadminUser struct {
	goadminUserDo goadminUserDo

	ALL           field.Asterisk
	ID            field.Int32
	Username      field.String
	Password      field.String
	Name          field.String
	Avatar        field.String
	RememberToken field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (g goadminUser) Table(newTableName string) *goadminUser {
	g.goadminUserDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goadminUser) As(alias string) *goadminUser {
	g.goadminUserDo.DO = *(g.goadminUserDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goadminUser) updateTableName(table string) *goadminUser {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.Username = field.NewString(table, "username")
	g.Password = field.NewString(table, "password")
	g.Name = field.NewString(table, "name")
	g.Avatar = field.NewString(table, "avatar")
	g.RememberToken = field.NewString(table, "remember_token")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *goadminUser) WithContext(ctx context.Context) *goadminUserDo {
	return g.goadminUserDo.WithContext(ctx)
}

func (g goadminUser) TableName() string { return g.goadminUserDo.TableName() }

func (g goadminUser) Alias() string { return g.goadminUserDo.Alias() }

func (g goadminUser) Columns(cols ...field.Expr) gen.Columns { return g.goadminUserDo.Columns(cols...) }

func (g *goadminUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goadminUser) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["username"] = g.Username
	g.fieldMap["password"] = g.Password
	g.fieldMap["name"] = g.Name
	g.fieldMap["avatar"] = g.Avatar
	g.fieldMap["remember_token"] = g.RememberToken
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminUser) clone(db *gorm.DB) goadminUser {
	g.goadminUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goadminUser) replaceDB(db *gorm.DB) goadminUser {
	g.goadminUserDo.ReplaceDB(db)
	return g
}

type goadminUserDo struct{ gen.DO }

func (g goadminUserDo) Debug() *goadminUserDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminUserDo) WithContext(ctx context.Context) *goadminUserDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminUserDo) ReadDB() *goadminUserDo {
	return g.Clauses(dbresolver.Read)
}

func (g goadminUserDo) WriteDB() *goadminUserDo {
	return g.Clauses(dbresolver.Write)
}

func (g goadminUserDo) Session(config *gorm.Session) *goadminUserDo {
	return g.withDO(g.DO.Session(config))
}

func (g goadminUserDo) Clauses(conds ...clause.Expression) *goadminUserDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminUserDo) Returning(value interface{}, columns ...string) *goadminUserDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goadminUserDo) Not(conds ...gen.Condition) *goadminUserDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminUserDo) Or(conds ...gen.Condition) *goadminUserDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminUserDo) Select(conds ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminUserDo) Where(conds ...gen.Condition) *goadminUserDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminUserDo) Order(conds ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminUserDo) Distinct(cols ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminUserDo) Omit(cols ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminUserDo) Join(table schema.Tabler, on ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminUserDo) Group(cols ...field.Expr) *goadminUserDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminUserDo) Having(conds ...gen.Condition) *goadminUserDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminUserDo) Limit(limit int) *goadminUserDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminUserDo) Offset(offset int) *goadminUserDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminUserDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminUserDo) Unscoped() *goadminUserDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminUserDo) Create(values ...*model.GoadminUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminUserDo) CreateInBatches(values []*model.GoadminUser, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminUserDo) Save(values ...*model.GoadminUser) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminUserDo) First() (*model.GoadminUser, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminUser), nil
	}
}

func (g goadminUserDo) Take() (*model.GoadminUser, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminUser), nil
	}
}

func (g goadminUserDo) Last() (*model.GoadminUser, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminUser), nil
	}
}

func (g goadminUserDo) Find() ([]*model.GoadminUser, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoadminUser), err
}

func (g goadminUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoadminUser, err error) {
	buf := make([]*model.GoadminUser, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminUserDo) FindInBatches(result *[]*model.GoadminUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminUserDo) Attrs(attrs ...field.AssignExpr) *goadminUserDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminUserDo) Assign(attrs ...field.AssignExpr) *goadminUserDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminUserDo) Joins(fields ...field.RelationField) *goadminUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goadminUserDo) Preload(fields ...field.RelationField) *goadminUserDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goadminUserDo) FirstOrInit() (*model.GoadminUser, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminUser), nil
	}
}

func (g goadminUserDo) FirstOrCreate() (*model.GoadminUser, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminUser), nil
	}
}

func (g goadminUserDo) FindByPage(offset int, limit int) (result []*model.GoadminUser, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goadminUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goadminUserDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goadminUserDo) Delete(models ...*model.GoadminUser) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goadminUserDo) withDO(do gen.Dao) *goadminUserDo {
	g.DO = *do.(*gen.DO)
	return g
}
