// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newGoadminRole(db *gorm.DB, opts ...gen.DOOption) goadminRole {
	_goadminRole := goadminRole{}

	_goadminRole.goadminRoleDo.UseDB(db, opts...)
	_goadminRole.goadminRoleDo.UseModel(&model.GoadminRole{})

	tableName := _goadminRole.goadminRoleDo.TableName()
	_goadminRole.ALL = field.NewAsterisk(tableName)
	_goadminRole.ID = field.NewInt32(tableName, "id")
	_goadminRole.Name = field.NewString(tableName, "name")
	_goadminRole.Slug = field.NewString(tableName, "slug")
	_goadminRole.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminRole.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminRole.fillFieldMap()

	return _goadminRole
}

type goadminRole struct {
	goadminRoleDo goadminRoleDo

	ALL       field.Asterisk
	ID        field.Int32
	Name      field.String
	Slug      field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (g goadminRole) Table(newTableName string) *goadminRole {
	g.goadminRoleDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goadminRole) As(alias string) *goadminRole {
	g.goadminRoleDo.DO = *(g.goadminRoleDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goadminRole) updateTableName(table string) *goadminRole {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.Name = field.NewString(table, "name")
	g.Slug = field.NewString(table, "slug")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *goadminRole) WithContext(ctx context.Context) *goadminRoleDo {
	return g.goadminRoleDo.WithContext(ctx)
}

func (g goadminRole) TableName() string { return g.goadminRoleDo.TableName() }

func (g goadminRole) Alias() string { return g.goadminRoleDo.Alias() }

func (g goadminRole) Columns(cols ...field.Expr) gen.Columns { return g.goadminRoleDo.Columns(cols...) }

func (g *goadminRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goadminRole) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["slug"] = g.Slug
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminRole) clone(db *gorm.DB) goadminRole {
	g.goadminRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goadminRole) replaceDB(db *gorm.DB) goadminRole {
	g.goadminRoleDo.ReplaceDB(db)
	return g
}

type goadminRoleDo struct{ gen.DO }

func (g goadminRoleDo) Debug() *goadminRoleDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminRoleDo) WithContext(ctx context.Context) *goadminRoleDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminRoleDo) ReadDB() *goadminRoleDo {
	return g.Clauses(dbresolver.Read)
}

func (g goadminRoleDo) WriteDB() *goadminRoleDo {
	return g.Clauses(dbresolver.Write)
}

func (g goadminRoleDo) Session(config *gorm.Session) *goadminRoleDo {
	return g.withDO(g.DO.Session(config))
}

func (g goadminRoleDo) Clauses(conds ...clause.Expression) *goadminRoleDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminRoleDo) Returning(value interface{}, columns ...string) *goadminRoleDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goadminRoleDo) Not(conds ...gen.Condition) *goadminRoleDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminRoleDo) Or(conds ...gen.Condition) *goadminRoleDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminRoleDo) Select(conds ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminRoleDo) Where(conds ...gen.Condition) *goadminRoleDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminRoleDo) Order(conds ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminRoleDo) Distinct(cols ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminRoleDo) Omit(cols ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminRoleDo) Join(table schema.Tabler, on ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminRoleDo) Group(cols ...field.Expr) *goadminRoleDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminRoleDo) Having(conds ...gen.Condition) *goadminRoleDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminRoleDo) Limit(limit int) *goadminRoleDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminRoleDo) Offset(offset int) *goadminRoleDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminRoleDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminRoleDo) Unscoped() *goadminRoleDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminRoleDo) Create(values ...*model.GoadminRole) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminRoleDo) CreateInBatches(values []*model.GoadminRole, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminRoleDo) Save(values ...*model.GoadminRole) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminRoleDo) First() (*model.GoadminRole, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRole), nil
	}
}

func (g goadminRoleDo) Take() (*model.GoadminRole, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRole), nil
	}
}

func (g goadminRoleDo) Last() (*model.GoadminRole, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRole), nil
	}
}

func (g goadminRoleDo) Find() ([]*model.GoadminRole, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoadminRole), err
}

func (g goadminRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoadminRole, err error) {
	buf := make([]*model.GoadminRole, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminRoleDo) FindInBatches(result *[]*model.GoadminRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminRoleDo) Attrs(attrs ...field.AssignExpr) *goadminRoleDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminRoleDo) Assign(attrs ...field.AssignExpr) *goadminRoleDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminRoleDo) Joins(fields ...field.RelationField) *goadminRoleDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goadminRoleDo) Preload(fields ...field.RelationField) *goadminRoleDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goadminRoleDo) FirstOrInit() (*model.GoadminRole, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRole), nil
	}
}

func (g goadminRoleDo) FirstOrCreate() (*model.GoadminRole, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoadminRole), nil
	}
}

func (g goadminRoleDo) FindByPage(offset int, limit int) (result []*model.GoadminRole, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goadminRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goadminRoleDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goadminRoleDo) Delete(models ...*model.GoadminRole) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goadminRoleDo) withDO(do gen.Dao) *goadminRoleDo {
	g.DO = *do.(*gen.DO)
	return g
}
