// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newMemberShelf(db *gorm.DB, opts ...gen.DOOption) memberShelf {
	_memberShelf := memberShelf{}

	_memberShelf.memberShelfDo.UseDB(db, opts...)
	_memberShelf.memberShelfDo.UseModel(&model.MemberShelf{})

	tableName := _memberShelf.memberShelfDo.TableName()
	_memberShelf.ALL = field.NewAsterisk(tableName)
	_memberShelf.ID = field.NewInt32(tableName, "id")
	_memberShelf.BookID = field.NewInt32(tableName, "book_id")
	_memberShelf.ChapterID = field.NewInt32(tableName, "chapter_id")
	_memberShelf.ReadDay = field.NewString(tableName, "read_day")
	_memberShelf.MemberID = field.NewInt32(tableName, "member_id")

	_memberShelf.fillFieldMap()

	return _memberShelf
}

type memberShelf struct {
	memberShelfDo memberShelfDo

	ALL       field.Asterisk
	ID        field.Int32
	BookID    field.Int32
	ChapterID field.Int32
	ReadDay   field.String // 浏览时间
	MemberID  field.Int32

	fieldMap map[string]field.Expr
}

func (m memberShelf) Table(newTableName string) *memberShelf {
	m.memberShelfDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberShelf) As(alias string) *memberShelf {
	m.memberShelfDo.DO = *(m.memberShelfDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberShelf) updateTableName(table string) *memberShelf {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.BookID = field.NewInt32(table, "book_id")
	m.ChapterID = field.NewInt32(table, "chapter_id")
	m.ReadDay = field.NewString(table, "read_day")
	m.MemberID = field.NewInt32(table, "member_id")

	m.fillFieldMap()

	return m
}

func (m *memberShelf) WithContext(ctx context.Context) *memberShelfDo {
	return m.memberShelfDo.WithContext(ctx)
}

func (m memberShelf) TableName() string { return m.memberShelfDo.TableName() }

func (m memberShelf) Alias() string { return m.memberShelfDo.Alias() }

func (m memberShelf) Columns(cols ...field.Expr) gen.Columns { return m.memberShelfDo.Columns(cols...) }

func (m *memberShelf) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberShelf) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["book_id"] = m.BookID
	m.fieldMap["chapter_id"] = m.ChapterID
	m.fieldMap["read_day"] = m.ReadDay
	m.fieldMap["member_id"] = m.MemberID
}

func (m memberShelf) clone(db *gorm.DB) memberShelf {
	m.memberShelfDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberShelf) replaceDB(db *gorm.DB) memberShelf {
	m.memberShelfDo.ReplaceDB(db)
	return m
}

type memberShelfDo struct{ gen.DO }

func (m memberShelfDo) Debug() *memberShelfDo {
	return m.withDO(m.DO.Debug())
}

func (m memberShelfDo) WithContext(ctx context.Context) *memberShelfDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberShelfDo) ReadDB() *memberShelfDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberShelfDo) WriteDB() *memberShelfDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberShelfDo) Session(config *gorm.Session) *memberShelfDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberShelfDo) Clauses(conds ...clause.Expression) *memberShelfDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberShelfDo) Returning(value interface{}, columns ...string) *memberShelfDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberShelfDo) Not(conds ...gen.Condition) *memberShelfDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberShelfDo) Or(conds ...gen.Condition) *memberShelfDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberShelfDo) Select(conds ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberShelfDo) Where(conds ...gen.Condition) *memberShelfDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberShelfDo) Order(conds ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberShelfDo) Distinct(cols ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberShelfDo) Omit(cols ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberShelfDo) Join(table schema.Tabler, on ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberShelfDo) LeftJoin(table schema.Tabler, on ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberShelfDo) RightJoin(table schema.Tabler, on ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberShelfDo) Group(cols ...field.Expr) *memberShelfDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberShelfDo) Having(conds ...gen.Condition) *memberShelfDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberShelfDo) Limit(limit int) *memberShelfDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberShelfDo) Offset(offset int) *memberShelfDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberShelfDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *memberShelfDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberShelfDo) Unscoped() *memberShelfDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberShelfDo) Create(values ...*model.MemberShelf) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberShelfDo) CreateInBatches(values []*model.MemberShelf, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberShelfDo) Save(values ...*model.MemberShelf) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberShelfDo) First() (*model.MemberShelf, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberShelf), nil
	}
}

func (m memberShelfDo) Take() (*model.MemberShelf, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberShelf), nil
	}
}

func (m memberShelfDo) Last() (*model.MemberShelf, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberShelf), nil
	}
}

func (m memberShelfDo) Find() ([]*model.MemberShelf, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberShelf), err
}

func (m memberShelfDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberShelf, err error) {
	buf := make([]*model.MemberShelf, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberShelfDo) FindInBatches(result *[]*model.MemberShelf, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberShelfDo) Attrs(attrs ...field.AssignExpr) *memberShelfDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberShelfDo) Assign(attrs ...field.AssignExpr) *memberShelfDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberShelfDo) Joins(fields ...field.RelationField) *memberShelfDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberShelfDo) Preload(fields ...field.RelationField) *memberShelfDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberShelfDo) FirstOrInit() (*model.MemberShelf, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberShelf), nil
	}
}

func (m memberShelfDo) FirstOrCreate() (*model.MemberShelf, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberShelf), nil
	}
}

func (m memberShelfDo) FindByPage(offset int, limit int) (result []*model.MemberShelf, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberShelfDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberShelfDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberShelfDo) Delete(models ...*model.MemberShelf) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberShelfDo) withDO(do gen.Dao) *memberShelfDo {
	m.DO = *do.(*gen.DO)
	return m
}
