// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fighthorse/sampleBookReader/domain/models/model"
)

func newMemberReader(db *gorm.DB, opts ...gen.DOOption) memberReader {
	_memberReader := memberReader{}

	_memberReader.memberReaderDo.UseDB(db, opts...)
	_memberReader.memberReaderDo.UseModel(&model.MemberReader{})

	tableName := _memberReader.memberReaderDo.TableName()
	_memberReader.ALL = field.NewAsterisk(tableName)
	_memberReader.ID = field.NewInt32(tableName, "id")
	_memberReader.MemberID = field.NewInt32(tableName, "member_id")
	_memberReader.BookID = field.NewInt32(tableName, "book_id")
	_memberReader.ChapterID = field.NewInt32(tableName, "chapter_id")
	_memberReader.LastUpdate = field.NewString(tableName, "last_update")

	_memberReader.fillFieldMap()

	return _memberReader
}

type memberReader struct {
	memberReaderDo memberReaderDo

	ALL        field.Asterisk
	ID         field.Int32
	MemberID   field.Int32  // 用户id
	BookID     field.Int32  // 书籍id
	ChapterID  field.Int32  // 章节id
	LastUpdate field.String // 最后一次更新

	fieldMap map[string]field.Expr
}

func (m memberReader) Table(newTableName string) *memberReader {
	m.memberReaderDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberReader) As(alias string) *memberReader {
	m.memberReaderDo.DO = *(m.memberReaderDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberReader) updateTableName(table string) *memberReader {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.MemberID = field.NewInt32(table, "member_id")
	m.BookID = field.NewInt32(table, "book_id")
	m.ChapterID = field.NewInt32(table, "chapter_id")
	m.LastUpdate = field.NewString(table, "last_update")

	m.fillFieldMap()

	return m
}

func (m *memberReader) WithContext(ctx context.Context) *memberReaderDo {
	return m.memberReaderDo.WithContext(ctx)
}

func (m memberReader) TableName() string { return m.memberReaderDo.TableName() }

func (m memberReader) Alias() string { return m.memberReaderDo.Alias() }

func (m memberReader) Columns(cols ...field.Expr) gen.Columns {
	return m.memberReaderDo.Columns(cols...)
}

func (m *memberReader) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberReader) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_id"] = m.MemberID
	m.fieldMap["book_id"] = m.BookID
	m.fieldMap["chapter_id"] = m.ChapterID
	m.fieldMap["last_update"] = m.LastUpdate
}

func (m memberReader) clone(db *gorm.DB) memberReader {
	m.memberReaderDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberReader) replaceDB(db *gorm.DB) memberReader {
	m.memberReaderDo.ReplaceDB(db)
	return m
}

type memberReaderDo struct{ gen.DO }

func (m memberReaderDo) Debug() *memberReaderDo {
	return m.withDO(m.DO.Debug())
}

func (m memberReaderDo) WithContext(ctx context.Context) *memberReaderDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberReaderDo) ReadDB() *memberReaderDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberReaderDo) WriteDB() *memberReaderDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberReaderDo) Session(config *gorm.Session) *memberReaderDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberReaderDo) Clauses(conds ...clause.Expression) *memberReaderDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberReaderDo) Returning(value interface{}, columns ...string) *memberReaderDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberReaderDo) Not(conds ...gen.Condition) *memberReaderDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberReaderDo) Or(conds ...gen.Condition) *memberReaderDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberReaderDo) Select(conds ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberReaderDo) Where(conds ...gen.Condition) *memberReaderDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberReaderDo) Order(conds ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberReaderDo) Distinct(cols ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberReaderDo) Omit(cols ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberReaderDo) Join(table schema.Tabler, on ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberReaderDo) LeftJoin(table schema.Tabler, on ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberReaderDo) RightJoin(table schema.Tabler, on ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberReaderDo) Group(cols ...field.Expr) *memberReaderDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberReaderDo) Having(conds ...gen.Condition) *memberReaderDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberReaderDo) Limit(limit int) *memberReaderDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberReaderDo) Offset(offset int) *memberReaderDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberReaderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *memberReaderDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberReaderDo) Unscoped() *memberReaderDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberReaderDo) Create(values ...*model.MemberReader) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberReaderDo) CreateInBatches(values []*model.MemberReader, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberReaderDo) Save(values ...*model.MemberReader) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberReaderDo) First() (*model.MemberReader, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberReader), nil
	}
}

func (m memberReaderDo) Take() (*model.MemberReader, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberReader), nil
	}
}

func (m memberReaderDo) Last() (*model.MemberReader, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberReader), nil
	}
}

func (m memberReaderDo) Find() ([]*model.MemberReader, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberReader), err
}

func (m memberReaderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberReader, err error) {
	buf := make([]*model.MemberReader, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberReaderDo) FindInBatches(result *[]*model.MemberReader, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberReaderDo) Attrs(attrs ...field.AssignExpr) *memberReaderDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberReaderDo) Assign(attrs ...field.AssignExpr) *memberReaderDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberReaderDo) Joins(fields ...field.RelationField) *memberReaderDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberReaderDo) Preload(fields ...field.RelationField) *memberReaderDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberReaderDo) FirstOrInit() (*model.MemberReader, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberReader), nil
	}
}

func (m memberReaderDo) FirstOrCreate() (*model.MemberReader, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberReader), nil
	}
}

func (m memberReaderDo) FindByPage(offset int, limit int) (result []*model.MemberReader, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberReaderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberReaderDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberReaderDo) Delete(models ...*model.MemberReader) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberReaderDo) withDO(do gen.Dao) *memberReaderDo {
	m.DO = *do.(*gen.DO)
	return m
}
