// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
	"github.com/fighthorse/sampleBookReader/goadmin/models"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// example end
var Generators = map[string]table.Generator{

	// generators end
	// admin/info/category
	"category": models.GetCategoryTable,
	"book":     models.GetBookTable,
	"chapter":  models.GetChapterTable,
	"comment":  models.GetCommentTable,
	"member":   models.GetMemberTable,
	"reader":   models.GetMemberReaderTable,
	"shelf":    models.GetMemberShelfTable,
	"feedback": models.GetFeedbackTable,
}
