// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthor = "author"

// Author mapped from table <author>
type Author struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthorName string `gorm:"column:author_name;not null;comment:作者姓名" json:"author_name"` // 作者姓名
	AuthorDesc string `gorm:"column:author_desc;not null;comment:作者简介" json:"author_desc"` // 作者简介
	AuthorDay  string `gorm:"column:author_day;not null;comment:作者入住时间" json:"author_day"` // 作者入住时间
	AuthorSex  string `gorm:"column:author_sex;comment:作者性别" json:"author_sex"`            // 作者性别
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
