// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:书籍id" json:"id"`    // 书籍id
	BookTitle    string `gorm:"column:book_title;not null;comment:书籍标题" json:"book_title"`         // 书籍标题
	BookDesc     string `gorm:"column:book_desc;not null;comment:书籍描述" json:"book_desc"`           // 书籍描述
	AuthorID     int32  `gorm:"column:author_id;comment:作者id" json:"author_id"`                    // 作者id
	ChapterTotal int32  `gorm:"column:chapter_total;comment:总章节数量" json:"chapter_total"`           // 总章节数量
	Copyright    string `gorm:"column:copyright;comment:版权方 出版社" json:"copyright"`                 // 版权方 出版社
	State        int32  `gorm:"column:state;default:1;comment:状态 默认1 待上架 5 已上架 0 删除" json:"state"` // 状态 默认1 待上架 5 已上架 0 删除
	CategoryID   int32  `gorm:"column:category_id;default:1;comment:分类id" json:"category_id"`      // 分类id
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
