// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryName string `gorm:"column:category_name;comment:分类名称" json:"category_name"`          // 分类名称
	ParentID     int32  `gorm:"column:parent_id;not null;comment:父分类" json:"parent_id"`          // 父分类
	CategoryDesc string `gorm:"column:category_desc;not null;comment:分类简介" json:"category_desc"` // 分类简介
	IsDel        bool   `gorm:"column:is_del;not null;comment:是否删除 1 是" json:"is_del"`           // 是否删除 1 是
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
