// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChapter = "chapter"

// Chapter mapped from table <chapter>
type Chapter struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BookID         int32  `gorm:"column:book_id;not null" json:"book_id"`
	ChapterName    string `gorm:"column:chapter_name;comment:章节标题" json:"chapter_name"`       // 章节标题
	ChapterContent string `gorm:"column:chapter_content;comment:章节内容" json:"chapter_content"` // 章节内容
	ChapterRank    int32  `gorm:"column:chapter_rank;comment:章节排序" json:"chapter_rank"`       // 章节排序
}

// TableName Chapter's table name
func (*Chapter) TableName() string {
	return TableNameChapter
}
