// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BookID      int32  `gorm:"column:book_id;not null" json:"book_id"`
	ChapterID   int32  `gorm:"column:chapter_id;not null" json:"chapter_id"`
	MemberID    int32  `gorm:"column:member_id;not null" json:"member_id"`
	CommentDesc string `gorm:"column:comment_desc;comment:评论内容" json:"comment_desc"`          // 评论内容
	CommentLike int32  `gorm:"column:comment_like;not null;comment:评论点赞" json:"comment_like"` // 评论点赞
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
