// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFeedback = "feedback"

// Feedback mapped from table <feedback>
type Feedback struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MemberID int32  `gorm:"column:member_id;comment:用户id" json:"member_id"` // 用户id
	Feed     string `gorm:"column:feed;comment:反馈内容" json:"feed"`           // 反馈内容
	FeedDay  string `gorm:"column:feed_day;comment:反馈时间" json:"feed_day"`   // 反馈时间
	Callback string `gorm:"column:callback;comment:回复内容" json:"callback"`   // 回复内容
	UserID   int32  `gorm:"column:user_id;comment:回复后台id" json:"user_id"`   // 回复后台id
}

// TableName Feedback's table name
func (*Feedback) TableName() string {
	return TableNameFeedback
}
