// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMember = "member"

// Member mapped from table <member>
type Member struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MemberName  string `gorm:"column:member_name;not null;comment:会员用户登录账户" json:"member_name"` // 会员用户登录账户
	MemberPwd   string `gorm:"column:member_pwd;not null;comment:登录密码" json:"member_pwd"`       // 登录密码
	MemberDesc  string `gorm:"column:member_desc;comment:用户自我介绍" json:"member_desc"`            // 用户自我介绍
	ReadBooks   int32  `gorm:"column:read_books;comment:阅读书籍数量" json:"read_books"`              // 阅读书籍数量
	RegisterDay string `gorm:"column:register_day;comment:注册时间" json:"register_day"`            // 注册时间
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
