// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberReader = "member_reader"

// MemberReader mapped from table <member_reader>
type MemberReader struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MemberID   int32  `gorm:"column:member_id;comment:用户id" json:"member_id"`       // 用户id
	BookID     int32  `gorm:"column:book_id;comment:书籍id" json:"book_id"`           // 书籍id
	ChapterID  int32  `gorm:"column:chapter_id;comment:章节id" json:"chapter_id"`     // 章节id
	LastUpdate string `gorm:"column:last_update;comment:最后一次更新" json:"last_update"` // 最后一次更新
}

// TableName MemberReader's table name
func (*MemberReader) TableName() string {
	return TableNameMemberReader
}
